#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2013 PAL Robotics SL.
# Released under the BSD License.
#
# Authors:
#   * Siegfried-A. Gevatter

import curses
import math
import os
import subprocess

import rospy
from geometry_msgs.msg import Twist
from std_msgs.msg import Empty, Bool

class Velocity(object):

    def __init__(self, min_velocity, max_velocity, num_steps):
        assert min_velocity > 0 and max_velocity > 0 and num_steps > 0
        self._min = min_velocity
        self._max = max_velocity
        self._num_steps = num_steps
        if self._num_steps > 1:
            self._step_incr = (max_velocity - min_velocity) / (self._num_steps - 1)
        else:
            # If num_steps is one, we always use the minimum velocity.
            self._step_incr = 0

    def __call__(self, value, step):
        """
        Takes a value in the range [0, 1] and the step and returns the
        velocity (usually m/s or rad/s).
        """
        if step == 0:
            return 0

        assert step > 0 and step <= self._num_steps
        max_value = self._min + self._step_incr * (step - 1)
        return value * max_value

class TextWindow():

    _screen = None
    _window = None
    _num_lines = None

    def __init__(self, stdscr, lines=10):
        self._screen = stdscr
        self._screen.nodelay(True)
        curses.curs_set(0)

        self._num_lines = lines

    def read_key(self):
        keycode = self._screen.getch()
        return keycode if keycode != -1 else None

    def clear(self):
        self._screen.clear()

    def write_line(self, lineno, message):
        if lineno < 0 or lineno >= self._num_lines:
            raise ValueError('lineno out of bounds')
        height, width = self._screen.getmaxyx()
        y = (height // self._num_lines) * lineno
        x = 10
        for text in message.split('\n'):
            text = text.ljust(width)
            self._screen.addstr(y, x, text)
            y += 1

    def refresh(self):
        self._screen.refresh()

    def beep(self):
        curses.flash()


class SimpleKeyTeleop():
    def __init__(self, interface):
        self._interface = interface
        self._namespace = '/bebop'
        self._pub_cmd = rospy.Publisher(self._namespace+'/cmd_vel', Twist)
        self._takeoff_cmd = rospy.Publisher(self._namespace+'/takeoff', Empty)
        self._land_cmd = rospy.Publisher(self._namespace+'/land', Empty)
        self._reset_cmd = rospy.Publisher(self._namespace+'/reset', Empty)
        self._flt_cmd = rospy.Publisher(self._namespace+'/flattrim', Empty)
        self._auto_cmd = rospy.Publisher(self._namespace+'/state_change', Bool)
        self._init_cmd = "parrot-gz model -m bebop2 -x 0 -y 0 -z 0.1 -R 0 -P 0 -Y 0"

        self._hz = rospy.get_param('~hz', 20)

        self._forward_rate = rospy.get_param('~forward_rate', 0.3)
        self._backward_rate = rospy.get_param('~backward_rate', 0.3)
        self._rotation_rate = rospy.get_param('~rotation_rate', 0.5)
        self._last_pressed = {}
        self._angular = 0
        self._linear_x = 0
        self._linear_y = 0
        self._linear_z = 0

        self.manual_mode = True

    movement_bindings = {
        curses.KEY_UP:    ( 1,  0,  0,  0), #Up Linear X+
        curses.KEY_DOWN:  (-1,  0,  0,  0), #Down Linear X-
        119:              ( 0,  1,  0,  0), #W Linear Z+
        115:              ( 0, -1,  0,  0), #S Linear Z-
        97:               ( 0,  0,  1,  0), #A Linear Y+
        100:              ( 0,  0, -1,  0), #D Linear Y-
        curses.KEY_LEFT:  ( 0,  0,  0,  1), #Left Angular Z+
        curses.KEY_RIGHT: ( 0,  0,  0, -1), #Right Angular Z-
    }

    def run(self):
        rate = rospy.Rate(self._hz)
        self._running = True
        while self._running:
            while True:
                keycode = self._interface.read_key()
                if keycode is None:
                    break
                self._key_pressed(keycode)
            self._set_velocity()
            self._publish()
            rate.sleep()

    def _get_twist(self, linear_x, linear_y, linear_z, angular):
        twist = Twist()
        twist.linear.x = linear_x
        twist.linear.y = linear_y
        twist.linear.z = linear_z
        twist.angular.z = angular
        return twist

    def _set_velocity(self):
        now = rospy.get_time()
        keys = []
        for a in self._last_pressed:
            if now - self._last_pressed[a] < 0.4:
                keys.append(a)
        linear_x = 0.0
        linear_y = 0.0
        linear_z = 0.0
        angular = 0.0
        for k in keys:
            lx,lz,ly, a = self.movement_bindings[k]
            linear_x += lx
            linear_y += ly
            linear_z += lz
            angular += a

        if linear_x > 0:
            linear_x = linear_x * self._forward_rate
        else:
            linear_x = linear_x * self._backward_rate

        linear_y = linear_y * self._forward_rate

        linear_z = linear_z * self._forward_rate

        angular = angular * self._rotation_rate
        self._angular = angular
        self._linear_x = linear_x
        self._linear_y = linear_y
        self._linear_z = linear_z

    def _key_pressed(self, keycode):
        if keycode == ord('q'):
            self._running = False
            rospy.signal_shutdown('Bye')
        elif keycode == ord('t') and self.manual_mode:
            self._takeoff_cmd.publish(Empty())
        elif keycode == ord('l'):
            self._land_cmd.publish(Empty())
        elif keycode == ord('r'):
            self._reset_cmd.publish(Empty())
        elif keycode == ord('i') and self.manual_mode:
            subprocess.call(self._init_cmd,shell=True)
            # self._flt_cmd.publish(Empty())
        elif keycode == ord('k'):
            twist = self._get_twist(0,0,0,0)
            self._pub_cmd.publish(twist)
            self._auto_cmd.publish(Bool(True))
            self.manual_mode = False
        elif keycode == ord('m'):
            self.manual_mode = True
            self._auto_cmd.publish(Bool(False))


        elif keycode in self.movement_bindings and self.manual_mode:
            self._last_pressed[keycode] = rospy.get_time()

    def _publish(self):
        self._interface.clear()
        if self.manual_mode:
            self._interface.write_line(1, 'Bebop2 Key Controller : Manual Mode')        
            self._interface.write_line(2, '----------------------------------------------------------------')        
            self._interface.write_line(3, 'Takeoff (T)                 | Linear X   (Up/Down)        {}'.format(self._linear_x))
            self._interface.write_line(4, 'Land (L)                    | Linear Y   (A/D)            {}'.format(self._linear_y))
            self._interface.write_line(5, 'Reset (R)                   | Linear Z   (W/S)            {}'.format(self._linear_z))
            self._interface.write_line(6, 'Initialize (I) (Sphinx)     | Angular Z  (Left/Right)     {}'.format(self._angular))
            self._interface.write_line(7, 'Switch to Autonomous Mode (K)                                       ')
            self._interface.write_line(8, '----------------------------------------------------------------')        
            self._interface.write_line(9, 'Q to quit')
        else:
            self._interface.write_line(1, 'Bebop2 Key Controller : Autonomous Mode')        
            self._interface.write_line(2, '----------------------------------------------------------------')        
            self._interface.write_line(3, 'Land (L)                    | Emergency Reset (R)               ')
            self._interface.write_line(5, 'Switch to Manual Mode (M)                                       ')
            self._interface.write_line(6, '----------------------------------------------------------------')        
            self._interface.write_line(7, 'Q to quit')
        self._interface.refresh()


        cmd_vels = [self._linear_x, self._linear_y, self._linear_z, self._angular]
        if not self.manual_mode:
            return
            
        twist = self._get_twist(*cmd_vels)
        self._pub_cmd.publish(twist)


def main(stdscr):
    rospy.init_node('key_teleop')
    app = SimpleKeyTeleop(TextWindow(stdscr))
    app.run()

if __name__ == '__main__':
    port_sphinx = 11345
    port_gazebo = 11346
    os.environ["GAZEBO_MASTER_URI"] = "http://localhost:{}".format(port_sphinx)
    try:
        curses.wrapper(main)
    except rospy.ROSInterruptException:
        pass
