#! /usr/bin/env python3


import os
import subprocess
import time

import rospy
import rospkg

def launch_sphinx(world_path,drone_path):
    sphinx_cmd = " ".join(["sphinx",world_path,drone_path])
    print("Sphinx Cmd ",sphinx_cmd)
    sphinx_process = subprocess.Popen(sphinx_cmd,shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True)
    for line in iter(sphinx_process.stdout.readline, ""):
        if "All drones instantiated" in line:
            rospy.loginfo("[GYM] Drone Instantiated")
            return

    raise RuntimeError("Drone Failed to Instantiate")


rospack = rospkg.RosPack()

drone_path = os.path.join(rospack.get_path('bebop2_control'),"sphinx/bebop2.drone")
world_path = os.path.join(rospack.get_path('bebop2_control'),"sphinx/empty.world")

launch_sphinx(world_path,drone_path)