#! /usr/bin/env python3


import os
import subprocess
import time

import rospy
import rospkg

def launch_sphinx(world_path,drone_path):
    sphinx_cmd = " ".join(["sphinx",world_path,drone_path])
    print("sphinx_cmd = ",sphinx_cmd)
    sphinx_process = subprocess.Popen(sphinx_cmd,shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True)
    for line in iter(sphinx_process.stdout.readline, ""):
        if "All drones instantiated" in line:
            rospy.loginfo("Drone Instantiated")
            rospy.set_param('sphinx_started', True)
            return

    raise RuntimeError("Drone Failed to Instantiate")


rospy.init_node("sphinx_node")

rospack = rospkg.RosPack()

drone_path = os.path.join(rospack.get_path('bebop2_control'),"sphinx/bebop2.drone")
world_path = os.path.join(rospack.get_path('bebop2_control'),"sphinx/outdoor_1.world")

launch_sphinx(world_path,drone_path)

# Set Battery Decay to Zero
batt_cmd = '''echo '{"jsonrpc": "2.0", "method": "SetParam", "params": {"machine":"bebop_a", "object":"lipobattery/lipobattery", "parameter":"discharge_speed_factor", "value":"0"}, "id": 1}' | curl -d @- http://localhost:8383 | python -m json.tool'''
subprocess.call(batt_cmd,shell=True)

rospy.spin()